### ISSUE TITLE
Error importing model

### ISSUE THREAD

**Issue by davidthomas411** [davidpagnon/Pose2Sim_Blender#4]
It seems like the use of os.path.basename() to find the model file doesn't work well on either windows or mac os.  If I change the os.path.basename() to os.path.basename(osim_path) it imports the model, but then the rest of the code doesn't seem to be able to find the correct collection in blender - any ideas?

--
Python: Traceback (most recent call last):
  File "/Users/thomasd2/Library/Application Support/Blender/4.0/scripts/addons/Pose2Sim_Blender/__init__.py", line 278, in execute
    model.import_model(osim_path,stlRoot=stlFolder)
  File "/Users/thomasd2/Library/Application Support/Blender/4.0/scripts/addons/Pose2Sim_Blender/Pose2Sim_Blender/model.py", line 97, in import_model
    collection = bpy.data.collections.new('osimModel_'+os.path.basename())
TypeError: basename() missing 1 required positional argument: 'p'
--

ps - i had to import CollectionsProperty to get the addon to load in blender. I added this to the import line in __init__.py as follows;
from bpy.props import IntProperty, BoolProperty, EnumProperty, StringProperty, CollectionProperty

**Comment by davidpagnon** [comment]
Hi Thomas, 
I just realized that was not "watching" the repository and that I did not get any update from issues, sorry about the delay! 
I also realized that I somehow messed up and merged different versions of the code. 
Please remove the add-on, install it again, and tell me if this works better!
