### ISSUE TITLE
Error importing motion

### ISSUE THREAD

**Issue by davidthomas411** [davidpagnon/Pose2Sim_Blender#5]
Error on motion import - both csv and mot files, both with example data and my own data.

"line 166, in apply_mot_to_model
    b_iterated = [o.name for o in collection.objects if o.name.startswith(b.getName())][0]
IndexError: list index out of range"

**Comment by davidpagnon** [comment]
I can't reproduce the issue, can you tell me precisely what you did?
- Did you reinstall it upon my last answer?
- Did you first open a model, then select it in the outliner, and then open a motion?

**Comment by davidpagnon** [comment]
Actually, I think your model has not been imported correctly.

- Which version of OpenSim is installed?
- In `"C:\Users\david\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Pose2Sim_Blender\Pose2Sim_Blender\model.py"`, can you add:
`print(geometry_directories)` line 111?
- Can you check the Blender console (Window -> Toggle System Console) and tell me what is the last message before the error starting with Ìmporting ****`?

**Comment by davidthomas411** [comment]
My mistake - I wasn't correctly selecting the model in the outliner - now it works everytime!! Closing the issue- thanks for your support.
